name: Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        name: Test (${{ matrix.os }}, Node v${{ matrix.node }})
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                node: [18, 20]

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  submodules: true

            - name: Install Node.js ${{ matrix.node }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}

            - name: Setup PNPM
              uses: pnpm/action-setup@v3
              with:
                  run_install: true

            - name: Test
              run: pnpm test

            - name: Test installation
              run: |
                  pnpm link -g
                  # Just execution the binary and letting it exit successfully is enough
                  selflare --version
